-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-05-24 19:19:23 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE TABLE hotel (
    hotel_id                      NUMBER NOT NULL,
    hotel_adress                  VARCHAR2(100 BYTE) NOT NULL,
    hotel_name                    VARCHAR2(50 BYTE),
    additional_number_of_scoring  FLOAT
);
ALTER TABLE hotel ADD CONSTRAINT hotel_pk PRIMARY KEY ( hotel_id );

CREATE TABLE reviewer (
    reviewer_id           NUMBER NOT NULL,
    reviewer_score        FLOAT,
    reviewer_nationality  VARCHAR2(40 BYTE)
);

ALTER TABLE reviewer ADD CONSTRAINT reviewer_pk PRIMARY KEY ( reviewer_id );

CREATE TABLE reviews (
    review_id                NUMBER NOT NULL,
    hotel_address            VARCHAR2(100 BYTE),
    average_score            FLOAT,
    review_date              DATE,
    negative_review          VARCHAR2(1500 BYTE),
    positive_review          VARCHAR2(1500 BYTE),
    total_number_of_reviews  INTEGER,
    hotel_id                 NUMBER NOT NULL,
    reviewer_id              NUMBER NOT NULL
);

ALTER TABLE reviews
    ADD CONSTRAINT reviews_pk PRIMARY KEY ( hotel_id,reviewer_id );

ALTER TABLE reviews
    ADD CONSTRAINT reviews_hotel_fk FOREIGN KEY ( hotel_id )
        REFERENCES hotel( hotel_id );

ALTER TABLE reviews
    ADD CONSTRAINT reviews_reviewer_fk FOREIGN KEY ( reviewer_id )
        REFERENCES reviewer ( reviewer_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
